# Generated by Django 3.2 on 2023-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='User Name')),
                ('useremail', models.CharField(max_length=50, verbose_name='User Email')),
                ('userphone', models.CharField(max_length=50, verbose_name='User Phone')),
                ('userpassword', models.CharField(max_length=50, verbose_name='User Password')),
                ('userConfpassword', models.CharField(max_length=50, verbose_name='Confirm Password')),
            ],
        ),
    ]
