# Generated by Django 3.2 on 2023-03-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_signup',
            name='acno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ac no.'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='adhaar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adhaar No.'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='adhaar_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adhaar Link'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='altphone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternate Phone'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='birth_state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Birth State'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='blood',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='board',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Board/University'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='caste_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Caste Category'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dob'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='dop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date Of Passing'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='exam_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Exam Name'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='examlevel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Exam Level'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Father First Name'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Last Name'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Father middle Name'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Name'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Occupation'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='full_nominee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Nominee Name'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='gardian_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gardian No.'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='gram_p',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gram Panchayat'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='h_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='House No'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='id_proof',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id Proof'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='is_diff_abled',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Is Different Abled'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name/ Surname'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='medium_of_instru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Medium Of Instruction'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother Name'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='mother_tougue',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother tougue'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='ncc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NCC'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='nominee_adhar_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nominee Aadhaar No'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='nominee_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nominee AGE'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='nominee_dob',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nominee DOB'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='nominee_mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nominee Mobile No'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='nominee_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nominee Relation With Student'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='op_mark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Optained Marks'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='paddress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='perc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Percentage'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='pincode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pin Code'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='place_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Place Birth'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='schoolarship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Schoolarship'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='sel_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Select Course'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='social_res',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Social Reservation'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='sport_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sports Person'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='stu_photo',
            field=models.FileField(blank=True, null=True, upload_to='student_photo', verbose_name='Student Photo'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='stu_signature',
            field=models.FileField(blank=True, null=True, upload_to='student_signature', verbose_name='Student Signature'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='subcast',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub Cast'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='tehsil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tehsil'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='total_mark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Total Marks'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='uni_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='University Reg No.'),
        ),
        migrations.AddField(
            model_name='student_signup',
            name='yop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Year Of Passing'),
        ),
    ]
