# Generated by Django 3.2 on 2023-03-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_form', '0002_auto_20230322_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_signup',
            old_name='username',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='student_signup',
            old_name='userpassword',
            new_name='userPassword',
        ),
        migrations.RemoveField(
            model_name='student_signup',
            name='email',
        ),
    ]
