# Generated by Django 3.2 on 2023-03-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_form', '0003_auto_20230323_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_signup',
            name='userName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User Name'),
        ),
    ]
