# Generated by Django 3.2 on 2023-03-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_form', '0004_alter_student_signup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_signup',
            name='userPassword',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User Password'),
        ),
    ]
