# Generated by Django 3.2 on 2023-03-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_form', '0005_alter_student_signup_userpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_signup',
            name='application_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Application Status'),
        ),
    ]
