# Generated by Django 3.2 on 2023-03-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_form', '0008_alter_student_signup_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_signup',
            old_name='userName',
            new_name='stu_userName',
        ),
        migrations.RenameField(
            model_name='student_signup',
            old_name='userPassword',
            new_name='stu_userPassword',
        ),
    ]
