# Generated by Django 3.2 on 2023-03-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_form', '0009_auto_20230325_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_signup',
            old_name='stu_userPassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student_signup',
            old_name='stu_userName',
            new_name='username',
        ),
    ]
