# Generated by Django 4.1.7 on 2023-05-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_form', '0010_auto_20230325_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_signup',
            name='application_status',
        ),
    ]
